# Generated by Django 4.2.6 on 2024-02-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
