# Generated by Django 4.2.16 on 2024-10-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aminoacidcomposition',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aminoacids', to='main.products'),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='main.products'),
        ),
        migrations.AlterField(
            model_name='fatacidcompositionofmeal',
            name='fat_acid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lipid_name', to='main.fatacids', verbose_name='Вид жирнокислоты'),
        ),
        migrations.AlterField(
            model_name='fatacidcompositionofmeal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatacids', to='main.products'),
        ),
        migrations.AlterField(
            model_name='fatacidcompositionofmeal',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fat_acid_types', to='main.fatacidstype', verbose_name='Тип жирных кислоты'),
        ),
        migrations.AlterField(
            model_name='mineralcomposition',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minerals', to='main.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='category_name', to='main.categories', verbose_name='Категория продукта'),
        ),
    ]
